BattingCols = {"playerID" : "personID", 'G' : 'Games', 'yearID' : 'year',
                                'AB' : 'AtBats',
                                'R' : 'Runs',
                                'lgID' : 'leagueID',
                                'H' : 'Hits',
                                '2B' : 'Doubles',
                                '3B' : 'Triples',
                                'HR' : 'HomeRuns',
                                'RBI' : 'RunsBattedIn',
                                'SB' : 'StolenBases',
                                'CS' : 'CaughtStealing',
                                'BB' : 'BaseOnBalls',
                                'SO' : 'StrikeOuts',
                                'IBB' : 'IntentionalWalks',
                                'HBP' : 'HitByPitch',
                                'SH' : 'SacrificeHits',
                                'SF' : 'SacrificeFlies',
                                'GIDP' : 'GroundedIntoDoublePlays'}

ManagerCols = {'playerID' : 'personID',
                                'lgID' : 'leagueID',
                                'yearID' : 'year',
                                'G' : 'GamesManaged',
                                'W' : 'Wins',
                                'L' : 'Losses'}

PitchingCols = {'playerID' :       'personID',
                'yearID'   :      'year',
                'lgID'     :      'leagueID',
                'W'         :     'Wins',
                'L'         :     'Losses',
                'G'         :     'Games',
                'GS'        :     'GamesStarted',
                'CG'        :     'CompleteGames',
                'SHO'       :     'Shutouts',
                'SV'        :     'Saves',
                'IPOuts'    :     'OutsPitched',
                'H'         :     'Hits',
                'ER'        :     'EarnedRuns',
                'HR'        :     'Homeruns',
                'BB'        :     'Walks',
                'SO'        :     'Strikeouts',
                'BAOpp'     :     'OpponentsBattingAvg',
                'ERA'       :     'EarnedRunAvg',
                'IBB'       :     'IntentionalWalks',
                'WP'        :     'WildPitches',
                'HBP'       :     'BattersHitByPitch',
                'BK'        :     'Balks',
                'BFP'       :     'BattersFacedByPitcher',
                'GF'        :     'GamesFinished',
                'R'         :     'RunsAllowed',
                'SH'        :     'SacrificesByOpposingBatters',
                'SF'        :     'SacrificeFliesByOpposingBatters',
                'GIDP'      :     'GIDPByOpposingBatter'}

FieldingCols = {'playerID'  :     'personID',
                'yearID'    :     'year',
                'lgID'      :     'leagueID',
                'POS'      :      'Position',
                'G'        :      'Games',
                'GS'       :      'GamesStarted',
                'PO'       :      'Putouts',
                'A'        :      'Assists',
                'E'        :      'Errors',
                'DP'       :      'DoublePlays',
                'TP'       :      'TriplePlays',
                'PB'       :      'PassedBallsByCatchers',
                'WP'       :      'WildPitchesByCatchers',
                'SB'       :      'OpponentStolenBasesByCatchers',
                'CS'       :      'OpponentsCaughtStealingByCatchers',
                'ZR'       :      'ZoneRating'}

TeamsCols = {'yearID' : 'year',
             'lgID' : 'leagueID',
             'divID' : 'divisionID',
             'G' : 'GamesPlayed',
             'Ghome' : 'GamesPlayedAtHome',
             'W' : 'Wins',
             'L' : 'Losses',
             'DivWin' : 'DivisionWinner',
             'WCWin' : 'WildcardWinner',
             'LgWin' : 'LeagueChampion',
             'WSWin' : 'WorldSeriesWinner',
             'R' : 'Runs',
             'AB' : 'AtBats',
             'H' : 'HitsByBatters',
             '2B' : 'Doubles',
             '3B' : 'Triples',
             'HR' : 'HomeRunsByBatters',
             'BB' : 'WalksByBatters',
             'SO' : 'StrikeoutsByBatters',
             'SB' : 'StolenBases',
             'CS' : 'CaughtStealing',
             'HBP' : 'BattersHitByPitch',
             'SF' : 'SacrificeFlies',
             'RA' : 'OpponentsRunsScored',
             'ER' : 'EarnedRunsAllowed',
             'ERA' : 'EarnedRunAvg',
             'CG' : 'CompleteGames',
             'SHO' : 'Shutouts',
             'SV' : 'Saves',
             'IPouts' : 'OutsPitched',
             'HA' : 'HitsAllowed',
             'HRA' : 'HomeRunsAllowed',
             'BBA' : 'WalksAllowed',
             'SOA' : 'StrikeoutsByPitchers',
             'E' : 'Errors',
             'park' : 'parkName',
             'DP' : 'DoublePlays',
             'FP' : 'FieldingPercentage',
             'BPF' : 'ThreeYearParkFactorBatters',
             'PPF' : 'ThreeYearParkFactorPitchers'
}

AppearancesCols = {
'playerID'  :     'personID',
'lgID'      :     'leagueID',
'yearID'    :     'year',
'G_all'     :     'TotalGamesPlayed',
'GS'        :     'GamesStarted',
'G_batting' :     'GamesPlayerBatted',
'G_defense' :     'GamesPlayerOnDefense',
'G_p'       :     'GamesAsPitcher',
'G_c'       :     'GamesAsCatcher',
'G_1b'      :     'GamesAsFirstBaseman',
'G_2b'      :     'GamesAsSecondBaseman',
'G_3b'      :     'GamesAsThirdBaseman',
'G_ss'      :     'GamesAsShortstop',
'G_lf'      :     'GamesAsLeftfielder',
'G_cf'      :     'GamesAsCenterfielder',
'G_rf'      :     'GamesAsRightfielder',
'G_of'      :     'GamesAsOutfielder',
'G_dh'      :     'GamesAsDesignatedHitter',
'G_ph'      :     'GamesAsPinchHitter',
'G_pr'      :     'GamesAsPinchRunner'
}

FieldingOFCols = {
'Glf'     :      'GamesPlayedLeftField',
'Gcf'     :       'GamesPlayedCenterField',
'Grf'     :       'GamesPlayedRightField',
'playerID' : 'personID',
'lgID' : 'leagueID',
'yearID' : 'year'
}

FieldingOFSplitCols = {
'playerID' : 'personID',
'lgID' : 'leagueID',
'yearID' : 'year',
'lgID'   :        'leagueID',
'POS'      :      'Position',
'G'        :      'Games',
'GS'       :      'GamesStarted',
'PO'       :      'Putouts',
'A'        :      'Assists',
'E'        :      'Errors',
'DP'       :      'DoublePlays'
}

HomeGamesCols = {
'year.key'	 :	'year',
'league.key' :	'leagueID',
'team.key'	 :	'teamID',
'park.key'	 :	'parkID',
'span.first' :  'debutGameDate',
'span.last'	 :	'endGameDate',
'games'      :  'gamesPlayed',
'openings'   :  'datesPlayed'
}

TeamsHalfCols = {
'playerID' : 'personID',
'lgID' : 'leagueID',
'yearID' : 'year',
'divID' : 'divisionID',
'G'    :   'GamesPlayed',
'W'    :   'Wins',
'L'    :   'Losses'
}