BattingCols = {"playerID" : "personID", 'G' : 'Games',
                                'AB' : 'AtBats',
                                'R' : 'Runs',
                                'lgID' : 'leagueID',
                                'H' : 'Hits',
                                '2B' : 'Doubles',
                                '3B' : 'Triples',
                                'HR' : 'HomeRuns',
                                'RBI' : 'RunsBattedIn',
                                'SB' : 'StolenBases',
                                'CS' : 'CaughtStealing',
                                'BB' : 'BaseOnBalls',
                                'SO' : 'StrikeOuts',
                                'IBB' : 'IntentionalWalks',
                                'HBP' : 'HitByPitch',
                                'SH' : 'SacrificeHits',
                                'SF' : 'SacrificeFlies',
                                'GIDP' : 'GroundedIntoDoublePlays'}

ManagerCols = {'playerID' : 'personID',
                                'lgID' : 'leagueID',
                                'yearID' : 'year',
                                'G' : 'GamesManaged',
                                'W' : 'Wins',
                                'L' : 'Losses'}

PitchingCols = {'playerID' :       'personID',
                'lgID'     :      'leagueID',
                'W'         :     'Wins',
                'L'         :     'Losses',
                'G'         :     'Games',
                'GS'        :     'GamesStarted',
                'CG'        :     'CompleteGames',
                'SHO'       :     'Shutouts',
                'SV'        :     'Saves',
                'IPOuts'    :     'OutsPitched',
                'H'         :     'Hits',
                'ER'        :     'EarnedRuns',
                'HR'        :     'Homeruns',
                'BB'        :     'Walks',
                'SO'        :     'Strikeouts',
                'BAOpp'     :     'OpponentsBattingAvg',
                'ERA'       :     'EarnedRunAvg',
                'IBB'       :     'IntentionalWalks',
                'WP'        :     'WildPitches',
                'HBP'       :     'BattersHitByPitch',
                'BK'        :     'Balks',
                'BFP'       :     'BattersFacedByPitcher',
                'GF'        :     'GamesFinished',
                'R'         :     'RunsAllowed',
                'SH'        :     'SacrificesByOpposingBatters',
                'SF'        :     'SacrificeFliesByOpposingBatters',
                'GIDP'      :     'GIDPByOpposingBatter'}

FieldingCols = {'playerID'  :     'personID',
                'lgID'      :     'leagueID',
                'Pos'      :      'Position',
                'G'        :      'Games',
                'GS'       :      'GamesStarted',
                'PO'       :      'Putouts',
                'A'        :      'Assists',
                'E'        :      'Errors',
                'DP'       :      'DoublePlays',
                'PB'       :      'PassedBallsByCatchers',
                'WP'       :      'WildPitchesByCatchers',
                'SB'       :      'OpponentStolenBasesByCatchers',
                'CS'       :      'OpponentsCaughtStealingByCatchers',
                'ZR'       :      'ZoneRating'}
